name: benchmark-aware-wgs
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - pyyaml

  - fastqc
  - multiqc
  - fastp

  - bwa-mem2
  - samtools
  - bcftools
  - htslib

  - rtg-tools
